#!/bin/bash
echo Création volume
docker volume create sae103

echo Installation des scripts dans volume
docker container run -d --name sae103-tmp -v sae103:/data php-cli74 tail -f /dev/null
docker cp scraper.php sae103-tmp:/data
docker cp fetcher.php sae103-tmp:/data
docker cp finish.sh sae103-tmp:/data

echo Fin installation
docker container stop sae103-tmp
docker container rm sae103-tmp

echo Lancement des conteneurs

docker container run -d --name sae103-scraper -e http_proxy="$http_proxy" -w /data -v sae103:/data php-cli74 ./scraper.php
docker container run -d --name sae103-fetcher -e http_proxy="$http_proxy" -w /data -v sae103:/data php-cli74 ./fetcher.php
docker container run -d --name sae103-finish -w /data -v sae103:/data php-cli74 ./finish.sh

echo Pret

# sleep 5

# docker container run -d --name sae103-1 -w /data -v sae103:/data php-cli74 tail -f /dev/null
# docker cp sae103-1:/data/liste .
# docker container stop sae103-1
# docker container rm sae103-1

# # docker container run --name sae103-2 -w /data -v sae103:/data php-cli74 which php
# # docker container logs sae103-2
# # docker container stop sae103-2
# # docker container rm sae103-2

# docker volume rm sae103